import {test,expect,type BrowserContext} from "@playwright/test";
import {mkdir,writeFile} from "node:fs/promises";
import {resolve} from "node:path";
import {seedAtlasFixtures} from "./personality-atlas-fixtures";
let fixtures:Awaited<ReturnType<typeof seedAtlasFixtures>>;
const base=process.env.E2E_BASE_URL??"http://127.0.0.1:4340";
const out=resolve(process.env.ATLAS_QA_OUTPUT??"../../outputs/atlas-integration");
const login=async(context:BrowserContext,index=0)=>context.addCookies([{name:"grani_session",value:fixtures[index]!.token,url:base,httpOnly:true,sameSite:"Lax"}]);
test.beforeAll(async()=>{fixtures=await seedAtlasFixtures();await mkdir(out,{recursive:true});await writeFile(resolve(out,"local-review-session.json"),JSON.stringify({url:base+"/report/"+fixtures[0]!.resultId,cookies:[{name:"grani_session",value:fixtures[0]!.token,url:base,httpOnly:true,sameSite:"Lax"}]}));});
test("desktop and mobile: real HTML, navigation, cards, scenarios and private server persistence",async({page,context})=>{
 await login(context);const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.setViewportSize({width:1440,height:1000});await page.goto("/report/"+fixtures[0]!.resultId);await expect(page.locator("[data-atlas-ready]")).toBeVisible();await expect(page.getByRole("heading",{name:"Мои грани инструкция к себе"})).toBeVisible();expect(await page.locator("[data-atlas-section]").count()).toBe(9);
 await page.screenshot({path:resolve(out,"desktop-overview.png")});
 await page.locator("#atlas-section-1").scrollIntoViewIfNeeded();await page.screenshot({path:resolve(out,"desktop-formula.png")});
 await page.getByRole("tab",{name:"Полезная фраза"}).click();await expect(page.locator("#atlas-scenario-text")).toContainText("Давай сохраним главную цель");
 await page.getByRole("tab",{name:"Предстоит непростой разговор"}).click();await expect(page.locator("#atlas-scenario-text")).toContainText("Хочу понять твою точку зрения");
 await page.locator("#atlas-step-0").focus();await page.keyboard.press("ArrowRight");await expect(page.locator("#atlas-step-1")).toBeFocused();
 await page.locator("#atlas-decision-note").fill("Сравнить два варианта завтра");await page.getByRole("checkbox",{name:/Отметить день 1 выполненным/}).check();await page.locator("#atlas-day-note").fill("Мой критерий готовности: показать черновик");
 await page.locator("#atlas-section-6").getByRole("button",{name:"Редактировать"}).click();await page.locator("#atlas-interaction-0").fill("Мне удобно сначала обдумать предложение");await page.getByRole("button",{name:"Применить к карточке"}).click();
 await page.locator("#atlas-section-9").getByRole("button",{name:"Редактировать"}).click();await page.locator("#atlas-memo-quote").fill("Сначала небольшой шаг, потом улучшение");await page.getByRole("button",{name:"Применить к памятке"}).click();await expect(page.getByRole("status",{name:""}).filter({hasText:"Сохранено в вашем аккаунте"})).toBeVisible();
 await page.reload();await expect(page.locator("#atlas-decision-note")).toHaveValue("Сравнить два варианта завтра");await expect(page.locator("#atlas-day-note")).toHaveValue("Мой критерий готовности: показать черновик");await expect(page.getByRole("checkbox",{name:/Отметить день 1 выполненным/})).toBeChecked();await expect(page.locator(".interaction-preview")).toContainText("Мне удобно сначала обдумать предложение");await expect(page.locator(".memo-card")).toContainText("Сначала небольшой шаг, потом улучшение");
 const api=await page.request.get("/api/report/"+fixtures[0]!.resultId+"/atlas");expect(api.status()).toBe(200);expect(api.headers()["cache-control"]).toBe("private, no-store");expect((await api.json()).draft.data.notes[0]).toContain("показать черновик");
 for(const width of [320,360,390,768,1024,1440,1920]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:resolve(out,"mobile-overview.png")});await page.locator(".mobile-nav summary").click();await page.locator(".mobile-nav").getByRole("link",{name:/План на 7 дней/}).click();await expect(page.locator(".mobile-nav")).not.toHaveAttribute("open");await page.locator("#atlas-section-8").scrollIntoViewIfNeeded();await page.screenshot({path:resolve(out,"mobile-week.png")});expect(errors).toEqual([]);
});
test("stale tab cannot overwrite server; reload version is explicit",async({page,context})=>{await login(context);await page.goto("/report/"+fixtures[0]!.resultId);await expect(page.locator("[data-atlas-ready]")).toBeVisible();const second=await context.newPage();await second.goto("/report/"+fixtures[0]!.resultId);await expect(second.locator("[data-atlas-ready]")).toBeVisible();await page.locator("#atlas-decision-note").fill("Первая вкладка");await expect(page.locator(".save-status")).toHaveText("Сохранено в вашем аккаунте");await second.locator("#atlas-decision-note").fill("Несохранённая вторая вкладка");await expect(second.locator(".save-status")).toHaveText("Есть другая версия на сервере");expect((await(await page.request.get("/api/report/"+fixtures[0]!.resultId+"/atlas")).json()).draft.data.decision).toBe("Первая вкладка");await expect(second.locator("#atlas-decision-note")).toHaveValue("Несохранённая вторая вкладка");second.once("dialog",d=>d.accept());await second.getByRole("button",{name:"Загрузить серверную версию"}).click();await expect(second.locator("#atlas-decision-note")).toHaveValue("Первая вкладка");await second.close();});
test("owner, purchase and origin restrictions apply in real application",async({page,context})=>{await login(context,1);expect((await page.request.get("/api/report/"+fixtures[0]!.resultId+"/atlas")).status()).toBe(404);await page.goto("/report/"+fixtures[1]!.resultId);await expect(page.locator(".hero-lead")).not.toHaveText("Идеи, которым ты умеешь придавать форму");expect((await page.request.put("/api/report/"+fixtures[1]!.resultId+"/atlas",{headers:{Origin:"https://foreign.example"},data:{}})).status()).toBe(403);await login(context,2);expect((await page.request.get("/api/report/"+fixtures[2]!.resultId+"/atlas")).status()).toBe(403);await page.goto("/report/"+fixtures[2]!.resultId);await expect(page).toHaveURL(/\/result\//);await login(context,3);await page.goto("/report/"+fixtures[3]!.resultId);await expect(page.getByText("Готовим разбор… Страница обновится сама.")).toBeVisible();await expect(page.locator("[data-atlas-section]")).toHaveCount(0);});

test("edits typed while loading conflict recovery survive",async({page,context})=>{await login(context);await page.goto("/report/"+fixtures[0]!.resultId);await expect(page.locator("[data-atlas-ready]")).toBeVisible();const api="/api/report/"+fixtures[0]!.resultId+"/atlas";const existing=(await(await page.request.get(api)).json()).draft;await page.request.put(api,{headers:{Origin:base},data:{expectedRevision:existing.revision,data:{...existing.data,decision:"Server newer"}}});await page.locator("#atlas-decision-note").fill("Stale version");await expect(page.locator(".save-status")).toHaveText("Есть другая версия на сервере");let release!:()=>void;const gate=new Promise<void>(r=>release=r);let received!:()=>void;const intercepted=new Promise<void>(r=>received=r);await page.route("**"+api,async route=>{if(route.request().method()==="GET"){received();await gate;}await route.continue();});page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Загрузить серверную версию"}).click();await intercepted;await page.locator("#atlas-decision-note").fill("Typed during load");release();await expect(page.locator(".save-status")).toHaveText("Есть другая версия на сервере");await expect(page.locator("#atlas-decision-note")).toHaveValue("Typed during load");});
test("internal navigation waits for the latest private edit",async({page,context})=>{await login(context);await page.goto("/report/"+fixtures[0]!.resultId);await expect(page.locator("[data-atlas-ready]")).toBeVisible();await page.locator("#atlas-decision-note").fill("Saved before leaving immediately");await page.getByRole("link",{name:"К результату",exact:true}).click();await expect(page).toHaveURL(/\/result\//);const draft=(await(await page.request.get("/api/report/"+fixtures[0]!.resultId+"/atlas")).json()).draft;expect(draft.data.decision).toBe("Saved before leaving immediately");});

test("slow save drains newer edits before leaving",async({page,context})=>{await login(context);await page.goto("/report/"+fixtures[0]!.resultId);await expect(page.locator("[data-atlas-ready]")).toBeVisible();const api="/api/report/"+fixtures[0]!.resultId+"/atlas";let release!:()=>void;const gate=new Promise<void>(r=>release=r);let received!:()=>void;const started=new Promise<void>(r=>received=r);let first=true;await page.route("**"+api,async route=>{if(route.request().method()==="PUT"&&first){first=false;received();await gate;}await route.continue();});await page.locator("#atlas-decision-note").fill("First snapshot");await started;await page.locator("#atlas-decision-note").fill("Latest snapshot while saving");await page.getByRole("link",{name:"К результату",exact:true}).click();expect(page.url()).toContain("/report/");release();await expect(page).toHaveURL(/\/result\//);expect((await(await page.request.get(api)).json()).draft.data.decision).toBe("Latest snapshot while saving");});
test("long private text wraps and offline changes stay available",async({page,context})=>{await login(context);await page.setViewportSize({width:320,height:800});await page.goto("/report/"+fixtures[0]!.resultId);await expect(page.locator("[data-atlas-ready]")).toBeVisible();await page.locator("#atlas-section-6").getByRole("button",{name:"Редактировать"}).click();await page.locator("#atlas-interaction-0").fill("W".repeat(2000));await page.getByRole("button",{name:"Применить к карточке"}).click();await page.locator("#atlas-section-9").getByRole("button",{name:"Редактировать"}).click();await page.locator("#atlas-memo-quote").fill("W".repeat(2000));await page.getByRole("button",{name:"Применить к памятке"}).click();await expect(page.locator(".save-status")).toHaveText("Сохранено в вашем аккаунте");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.route("**/api/report/*/atlas",route=>route.abort());await page.locator("#atlas-decision-note").fill("Offline local changes");await expect(page.locator(".save-status")).toHaveText("Сохранение не подтверждено");await expect(page.locator("#atlas-decision-note")).toHaveValue("Offline local changes");await expect(page.getByRole("button",{name:"Скачать черновик"})).toBeVisible();await page.getByRole("link",{name:"К результату",exact:true}).click();expect(page.url()).toContain("/report/");});

test("browser Back preserves offline and unapplied edits",async({page,context})=>{await login(context);const id=fixtures[0]!.resultId;await page.goto("/result/"+id);await page.waitForFunction(()=>Boolean(window.history.state?.__NA));await page.locator('a[href="/report/'+id+'"]').first().click();await expect(page.locator("[data-atlas-ready]")).toBeVisible();await page.route("**/api/report/*/atlas",route=>route.abort());await page.locator("#atlas-decision-note").fill("Offline note must survive Back");await expect(page.locator(".save-status")).toHaveText("Сохранение не подтверждено");await page.goBack();await expect(page).toHaveURL(/\/result\//);await page.goForward();await expect(page.locator("[data-atlas-ready]")).toBeVisible();await expect(page.locator("#atlas-decision-note")).toHaveValue("Offline note must survive Back");await page.unroute("**/api/report/*/atlas");await page.getByRole("button",{name:"Повторить сохранение"}).click();await expect(page.locator(".save-status")).toHaveText("Сохранено в вашем аккаунте");await page.locator("#atlas-section-9").getByRole("button",{name:"Редактировать"}).click();await page.locator("#atlas-memo-quote").fill("Unapplied memo must survive Back");await page.goBack();await expect(page).toHaveURL(/\/result\//);await page.goForward();await expect(page.locator("[data-atlas-ready]")).toBeVisible();await expect(page.locator("#atlas-memo-quote")).toHaveValue("Unapplied memo must survive Back");});
test("revert while PUT is pending remains protected",async({page,context})=>{await login(context);await page.goto("/report/"+fixtures[0]!.resultId);await expect(page.locator("[data-atlas-ready]")).toBeVisible();const previous=await page.locator("#atlas-decision-note").inputValue();let release!:()=>void;const gate=new Promise<void>(r=>release=r);let received!:()=>void;const started=new Promise<void>(r=>received=r);let first=true;await page.route("**/api/report/*/atlas",async route=>{if(route.request().method()==="PUT"&&first){first=false;received();await gate;}await route.continue();});await page.locator("#atlas-decision-note").fill("Pending temporary change");await started;await page.locator("#atlas-decision-note").fill(previous);await expect(page.locator(".save-status")).toHaveText("Сохраняем…");await page.getByRole("link",{name:"К результату",exact:true}).click();expect(page.url()).toContain("/report/");release();await expect(page).toHaveURL(/\/result\//);expect((await(await page.request.get("/api/report/"+fixtures[0]!.resultId+"/atlas")).json()).draft.data.decision).toBe(previous);});

test("unavailable tab storage is reported continuously",async({page,context})=>{await login(context);await page.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException("Blocked","SecurityError");};});await page.goto("/report/"+fixtures[0]!.resultId);await expect(page.locator("[data-atlas-ready]")).toBeVisible();await page.route("**/api/report/*/atlas",route=>route.abort());await page.locator("#atlas-decision-note").fill("Unsaved without storage");await expect(page.locator(".save-status")).toHaveText("Сохранение не подтверждено");await expect(page.locator(".storage-bar")).toContainText("Браузер запретил временное хранение");await page.locator("#atlas-section-9").getByRole("button",{name:"Редактировать"}).click();await page.locator("#atlas-memo-quote").fill("Editor without storage");await expect(page.locator("#atlas-memo-editor")).toContainText("Браузер запретил временное хранение");});
