import { beforeEach, expect, test, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
const mocks=vi.hoisted(()=>({result:vi.fn(),products:vi.fn(),load:vi.fn(),user:vi.fn(),view:vi.fn(),notFound:vi.fn(()=>{throw Error("404")}),redirect:vi.fn(()=>{throw Error("redirect")})}));
vi.mock("@grani/db",()=>({getResultForOwner:mocks.result,listOwnedProducts:mocks.products,loadAtlasDraft:mocks.load,getInviteForResult:vi.fn(async()=>null),listReports:vi.fn(async()=>[]),countFriendResponses:vi.fn()}));
vi.mock("@/server/db",()=>({getDb:()=>({})}));
vi.mock("@/server/viewer",()=>({requireUser:mocks.user}));
vi.mock("@/lib/report-view",()=>({buildReportPageView:mocks.view,REPORT_DISCLAIMER:"Disclaimer"}));
vi.mock("next/navigation",()=>({notFound:mocks.notFound,redirect:mocks.redirect}));
vi.mock("@/components/GemPortrait",()=>({GemPortrait:()=>null}));
vi.mock("@/components/BuyButton",()=>({BuyButton:()=>null}));
vi.mock("@/app/result/[id]/ShareCard",()=>({ShareCard:()=>null}));
vi.mock("@/components/AutoRefresh",()=>({AutoRefresh:()=>null}));
import ReportPage from "./page";
const full={portrait:"Existing portrait",strengths:["Existing strength"],blind_spots:[],manual:{work:[],fight:[],annoys:[]}};
beforeEach(()=>{vi.clearAllMocks();delete process.env.PERSONALITY_ATLAS_V2;mocks.user.mockResolvedValue({id:"owner",displayName:"Анна",gender:"female"});mocks.result.mockResolvedValue({id:"r",typeCode:"++--",scores:{openness:85,conscientiousness:90,extraversion:25,agreeableness:35,stability:65}});mocks.products.mockResolvedValue(["full"]);mocks.load.mockResolvedValue(null);mocks.view.mockReturnValue({full,preparing:false,friends:{state:"waiting",counter:"0 из 3"},chapters:[],bundle:null});});
const render=async()=>renderToStaticMarkup(await ReportPage({params:Promise.resolve({resultId:"r"})}));
test("flag off preserves original report without reading the draft table",async()=>{const html=await render();expect(html).toContain("Existing portrait");expect(html).not.toContain("Мои грани");expect(mocks.load).not.toHaveBeenCalled();});
test("flag on mounts atlas with real scores and preserves original report",async()=>{process.env.PERSONALITY_ATLAS_V2="1";const html=await render();expect(html).toContain("Мои грани");expect(html).toContain("Анна");expect(html).toContain("Existing portrait");expect(html.match(/<h1/g)).toHaveLength(1);expect(mocks.load).toHaveBeenCalledWith({},"r");});
test("pending report still uses original preparing state",async()=>{process.env.PERSONALITY_ATLAS_V2="1";mocks.view.mockReturnValue({full:null,preparing:true,friends:{state:"waiting",counter:"0 из 3"},chapters:[],bundle:null});expect(await render()).toContain("Готовим");expect(mocks.load).not.toHaveBeenCalled();});
test("foreign result and unpaid result cannot load private drafts",async()=>{process.env.PERSONALITY_ATLAS_V2="1";mocks.result.mockResolvedValueOnce(null);await expect(render()).rejects.toThrow("404");mocks.products.mockResolvedValueOnce([]);await expect(render()).rejects.toThrow("redirect");expect(mocks.load).not.toHaveBeenCalled();});
