import {afterEach,beforeEach,expect,test,vi} from "vitest";
import {claimTabWriter,clearTabDrafts,readPending,storePending} from "./atlas-tab-drafts";
const data=(decision:string)=>({done:Array(7).fill(false),notes:Array(7).fill(""),decision,interaction:["","",""],memo:{quote:"",items:Array(5).fill("")}});
let storage:Map<string,string>;
beforeEach(()=>{storage=new Map();vi.stubGlobal("sessionStorage",{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)});clearTabDrafts("r");});afterEach(()=>vi.unstubAllGlobals());
test("old save acknowledgement cannot clear a newer mounted writer's edits",()=>{claimTabWriter("r","old");storePending("r",{revision:0,data:data("B"),blocked:null},"old");claimTabWriter("r","new");storePending("r",{revision:0,data:data("C"),blocked:null},"new");storePending("r",null,"old");expect(readPending("r")?.data.decision).toBe("C");storePending("r",{revision:1,data:data("B"),blocked:"conflict"},"old");expect(readPending("r")?.data.decision).toBe("C");storePending("r",null,"new");expect(readPending("r")).toBeNull();});
test("storage failure is reported and a client-routing memory fallback remains",()=>{claimTabWriter("r","owner");vi.stubGlobal("sessionStorage",{getItem:()=>{throw Error("blocked")},setItem:()=>{throw Error("blocked")},removeItem:()=>{throw Error("blocked")}});expect(storePending("r",{revision:0,data:data("private"),blocked:"error"},"owner")).toBe(false);expect(readPending("r")?.data.decision).toBe("private");});
test("malformed browser content never becomes a draft",()=>{storage.set("grani-atlas-pending:r:applied",JSON.stringify({revision:0,data:{},blocked:null}));expect(readPending("r")).toBeNull();});

test("quota failure keeps newer memory over readable stale stored data",()=>{claimTabWriter("r","old");storePending("r",{revision:0,data:data("B"),blocked:null},"old");vi.stubGlobal("sessionStorage",{getItem:(k:string)=>storage.get(k)??null,setItem:()=>{throw Error("quota")},removeItem:(k:string)=>storage.delete(k)});expect(claimTabWriter("r","new")).toBe(false);expect(storePending("r",{revision:0,data:data("C"),blocked:"error"},"new")).toBe(false);expect(readPending("r")?.data.decision).toBe("C");});
