"use client";
import { useState } from "react";
import {usePrivateEditor, interactionEditorSchema, memoEditorSchema} from "./atlas-tab-drafts";
import type { AtlasDraftData } from "@grani/db";
import type { PersonalityAtlas } from "@/lib/personality-atlas";
import { Section } from "./AtlasPrimitives";
import type { UpdateAtlas } from "./AtlasPractices";

export function AtlasInteraction({resultId,data,update,displayName,notify}:{resultId:string;data:AtlasDraftData;update:UpdateAtlas;displayName:string;notify:(text:string)=>void}){
  const [editing,setEditing,storageAvailable]=usePrivateEditor(resultId,"interaction",interactionEditorSchema);
  const [selected,setSelected]=useState([true,true,true]),[fallback,setFallback]=useState("");
  const copy=async()=>{const text=data.interaction.filter((_,i)=>selected[i]).join("\n\n");if(!text){notify("Выбери хотя бы одну фразу.");return;}try{await navigator.clipboard.writeText(text);notify("Выбранные фразы скопированы. Ничего не опубликовано.");}catch{setFallback(text);}};
  return <Section number={6} label="Как со мной лучше взаимодействовать" title="Несколько слов обо мне" action={<span className="privacy-tag">Приватная карточка</span>}><p className="section-intro">Это твои слова. Измени текст и выбери только то, чем хочется добровольно поделиться.</p><div className="interaction-layout"><div className="interaction-preview"><p className="eyebrow gold">{displayName}</p><h3>Мне помогает ясность</h3>{data.interaction.map((text,i)=><p key={i}>{text}</p>)}<div className="preview-footer"><span>Никому не отправлено</span><span aria-hidden="true">◇</span></div></div><div className="interaction-controls"><div className="row between"><h3>Выбрать для копирования</h3><button type="button" className="text-button" aria-expanded={editing!==null} aria-controls="atlas-interaction-editor" onClick={()=>setEditing(editing?null:[...data.interaction])}>Редактировать</button></div>{["Цель и время обдумать","Конкретная обратная связь","Обсуждение разногласий"].map((label,i)=><label className="copy-option" key={label}><input type="checkbox" checked={selected[i]} onChange={e=>setSelected(before=>before.map((v,j)=>i===j?e.target.checked:v))}/>{label}</label>)}<button type="button" className="button primary" onClick={()=>void copy()}>Скопировать выбранное</button><p className="field-help">Копирование не создаёт ссылку и ничего не публикует. Скопированный текст можно отправить самостоятельно.</p>{fallback&&<><label className="field-label" htmlFor="atlas-copy-fallback">Браузер не разрешил копирование. Выдели текст вручную.</label><textarea id="atlas-copy-fallback" readOnly value={fallback} rows={6}/></>}<form id="atlas-interaction-editor" hidden={editing===null} data-atlas-editor-dirty={editing!==null?true:undefined} onSubmit={e=>{e.preventDefault();if(editing)update(before=>({...before,interaction:editing.map(t=>t.trim())}));setEditing(null);notify("Правки применены. Статус сохранения — вверху атласа.");}}>{!storageAvailable&&<p className="field-help" role="alert">Браузер запретил временное хранение. Примените правки и дождитесь серверного сохранения перед уходом.</p>}<p className="field-help" role="status">Правки редактора ещё не применены. Нажми «Применить к карточке», чтобы включить сохранение.</p>{editing?.map((text,i)=><div key={i}><label className="field-label" htmlFor={`atlas-interaction-${i}`}>Фраза {i+1}</label><textarea id={`atlas-interaction-${i}`} value={text} maxLength={2000} rows={3} onChange={e=>setEditing(before=>before!.map((t,j)=>i===j?e.target.value:t))}/></div>)}<div className="row"><button type="submit" className="button primary">Применить к карточке</button><button type="button" className="button ghost" onClick={()=>setEditing(null)}>Отмена</button></div></form></div></div></Section>;
}

export function AtlasMemo({resultId,data,update,model,displayName,typeName,notify}:{resultId:string;data:AtlasDraftData;update:UpdateAtlas;model:PersonalityAtlas;displayName:string;typeName:string;notify:(text:string)=>void}){
  const [editing,setEditing,storageAvailable]=usePrivateEditor(resultId,"memo",memoEditorSchema);
  const download=()=>{
    const text=`ГРАНИ · Мои грани — инструкция к себе\n${displayName} · ${typeName}\n${model.traits.map(t=>`${t.code}${t.value}`).join(" ")}\n\n${data.memo.quote}\n\n${model.memo.items.map((item,i)=>`${item.label}: ${data.memo.items[i]}`).join("\n\n")}\n\nРедакционные гипотезы для самонаблюдения. Не психологическая и не медицинская диагностика.\n`;
    const url=URL.createObjectURL(new Blob(["\uFEFF"+text],{type:"text/plain;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="Грани-моя-памятка.txt";document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);notify("Текстовая памятка подготовлена для скачивания.");
  };
  return <Section number={9} label="Моя личная памятка" title="То, что хочется взять с собой" action={<button type="button" className="button ghost" aria-expanded={editing!==null} aria-controls="atlas-memo-editor" onClick={()=>setEditing(editing?null:structuredClone(data.memo))}>Редактировать</button>}><div className="memo-card"><div className="memo-top"><span className="eyebrow gold">{displayName} · {typeName}</span><span aria-hidden="true">◇</span></div><blockquote>{data.memo.quote}</blockquote><dl>{model.memo.items.map((item,i)=><div className="memo-item" key={item.label}><dt>{item.label}</dt><dd>{data.memo.items[i]}</dd></div>)}</dl><div className="memo-footer"><span>Мои грани — инструкция к себе</span><span>Приватная памятка</span></div></div><form id="atlas-memo-editor" hidden={editing===null} data-atlas-editor-dirty={editing!==null?true:undefined} onSubmit={e=>{e.preventDefault();if(editing)update(before=>({...before,memo:{quote:editing.quote.trim(),items:editing.items.map(t=>t.trim())}}));setEditing(null);notify("Правки применены. Статус сохранения — вверху атласа.");}}>{!storageAvailable&&<p className="field-help" role="alert">Браузер запретил временное хранение. Примените правки и дождитесь серверного сохранения перед уходом.</p>}<p className="field-help" role="status">Правки редактора ещё не применены. Нажми «Применить к памятке», чтобы включить сохранение.</p>{editing&&<><label className="field-label" htmlFor="atlas-memo-quote">Главная фраза</label><textarea id="atlas-memo-quote" value={editing.quote} maxLength={2000} rows={3} onChange={e=>setEditing(before=>({...before!,quote:e.target.value}))}/>{model.memo.items.map((item,i)=><div key={item.label}><label className="field-label" htmlFor={`atlas-memo-${i}`}>{item.label}</label><textarea id={`atlas-memo-${i}`} value={editing.items[i]} maxLength={2000} rows={2} onChange={e=>setEditing(before=>({...before!,items:before!.items.map((text,j)=>i===j?e.target.value:text)}))}/></div>)}</>}<div className="row"><button type="submit" className="button primary">Применить к памятке</button><button type="button" className="button ghost" onClick={()=>setEditing(null)}>Отмена</button></div></form><div className="memo-actions"><button type="button" className="button primary" onClick={download}>Скачать памятку .txt</button><button type="button" className="button ghost" onClick={()=>notify("PDF-экспорт пока не подключён. Можно скачать текстовую памятку.")}>PDF · следующий этап</button><span className="muted">Публичная ссылка не создаётся.</span></div></Section>;
}
