"use client";
import { useState, type CSSProperties } from "react";
import type { PersonalityAtlas } from "@/lib/personality-atlas";
import type { AtlasDraftData } from "@grani/db";
import { ATLAS_COPY } from "./atlas-copy";
import { Section, Tabs } from "./AtlasPrimitives";

export type UpdateAtlas=(change:(before:AtlasDraftData)=>AtlasDraftData)=>void;
export function AtlasScenarios({model}:{model:PersonalityAtlas}){
  const [scenario,setScenario]=useState(0),[view,setView]=useState(0);const current=ATLAS_COPY.scenarios[scenario]!;
  const reaction=model.strengths[0]!.ruleIds.includes("R01")?current.reaction:`Что хочется сделать первым? Возможный ракурс для наблюдения: ${model.strengths[0]!.risk} Проверь, связано ли это с этой ситуацией; реакция может быть другой.`;
  return <Section number={7} label="Мои жизненные сценарии" title="Когда жизнь меняет условия"><p className="section-intro">Пять ситуаций, чтобы заметить привычную реакцию и попробовать другой ход. Это вопросы к наблюдению, а не прогноз по баллам.</p><div className="scenario-layout"><Tabs prefix="atlas-scenario" items={ATLAS_COPY.scenarios.map(s=>s.title)} selected={scenario} onSelect={setScenario} label="Пять жизненных ситуаций" panel="atlas-scenario-card" className="scenario-list" vertical/><div className="scenario-card" id="atlas-scenario-card" role="tabpanel" aria-labelledby={`atlas-scenario-${scenario}`} tabIndex={0}><p className="eyebrow gold">Ситуация 0{scenario+1} / 05</p><h3>{current.title}</h3><Tabs prefix="atlas-scenario-view" items={["Возможная реакция","Что попробовать","Полезная фраза"]} selected={view} onSelect={setView} label="Ракурс ситуации" panel="atlas-scenario-text" className="segmented scenario-switch"/><div id="atlas-scenario-text" role="tabpanel" aria-labelledby={`atlas-scenario-view-${view}`} tabIndex={0}>{view===2?<blockquote>«{current.phrase}»</blockquote>:<p>{view===0?reaction:current.practice}</p>}</div><p className="scenario-limit">Узнаёшь себя? Проверь в конкретной ситуации. Баллы не определяют твою реакцию.</p></div></div></Section>;
}
export function AtlasWeek({data,update}:{data:AtlasDraftData;update:UpdateAtlas}){
  const [day,setDay]=useState(0);const completed=data.done.filter(Boolean).length,percent=Math.round(completed/7*100),practice=ATLAS_COPY.days[day]!;
  const mark=(i:number,done:boolean)=>update(before=>({...before,done:before.done.map((v,j)=>i===j?done:v)}));
  return <Section number={8} label="Мой план на 7 дней" title="Маленькие действия. Больше понимания себя." action={<div className="progress-ring" role="img" aria-label={`Выполнено ${completed} из 7, ${percent} процентов`} style={{"--progress":`${percent}%`} as CSSProperties}><span>{percent}%</span><small>недели</small></div>}><p className="section-intro">Один эксперимент в день. Можно пропустить день, вернуться к заметкам или снять отметку. Это не оценка продуктивности.</p><div className="week-layout"><div className="week-list">{ATLAS_COPY.days.map((d,i)=><div className="day-row" key={d.title}><label className="day-check-label"><input type="checkbox" checked={data.done[i]} aria-label={`Отметить день ${i+1} выполненным: ${d.title}`} onChange={e=>mark(i,e.target.checked)}/></label><button type="button" className="day-select" aria-pressed={day===i} aria-controls="atlas-day-panel" onClick={()=>setDay(i)}><small>День 0{i+1}</small>{d.title}</button></div>)}</div><div className="day-panel" id="atlas-day-panel"><p className="eyebrow gold">День 0{day+1} / 07</p><h3>{practice.title}</h3><p>{practice.practice}</p><div className="day-question"><span className="eyebrow">Вопрос к себе</span><p>{practice.question}</p></div><label className="field-label" htmlFor="atlas-day-note">Мои наблюдения</label><textarea id="atlas-day-note" rows={4} maxLength={2000} value={data.notes[day]} onChange={e=>update(before=>({...before,notes:before.notes.map((text,i)=>i===day?e.target.value:text)}))} placeholder="Что получилось? Что хочется изменить?"/><button type="button" className="button primary" aria-pressed={data.done[day]} onClick={()=>mark(day,!data.done[day])}>{data.done[day]?"Снять отметку выполнения":"Отметить выполненным"}</button></div></div></Section>;
}
