"use client";
import { useState } from "react";
import type { PersonalityAtlas } from "@/lib/personality-atlas";
import { Section } from "./AtlasPrimitives";

export function AtlasFormula({model}:{model:PersonalityAtlas}){
  const [selected,setSelected]=useState(0);const traits=model.traits;
  const point=(i:number,ratio=1)=>{const angle=(-90+i*72)*Math.PI/180;return [170+Math.cos(angle)*112*ratio,157+Math.sin(angle)*112*ratio];};
  const polygon=(ratio:number)=>traits.map((_,i)=>point(i,ratio).join(",")).join(" ");
  return <Section number={1} label="Моя формула личности" title={model.formulaTitle}>
    <p className="section-intro">{model.formulaText}</p>
    <div className="formula-layout"><div className="radar-panel"><div className="panel-label">Пять моих граней <span>Баллы из 100</span></div><svg viewBox="0 0 340 320" role="img" aria-labelledby="atlas-radar-title atlas-radar-description"><title id="atlas-radar-title">Профиль Big Five</title><desc id="atlas-radar-description">{traits.map(t=>`${t.name}: ${t.value} из 100`).join(", ")}</desc>{[.25,.5,.75,1].map(r=><polygon key={r} points={polygon(r)} fill="none" stroke="var(--gold)" strokeOpacity={.2} strokeWidth={.7}/>)}{traits.map((t,i)=>{const [x,y]=point(i),[lx,ly]=point(i,1.2);return <g key={t.code}><line x1={170} y1={157} x2={x} y2={y} stroke="var(--gold)" strokeOpacity={.18}/><text x={lx} y={ly!+4} fill="var(--gold)" fontSize={11} textAnchor="middle" fontFamily="var(--font-body)">{t.code} {t.value}</text></g>;})}<polygon points={traits.map((t,i)=>point(i,t.value/100).join(",")).join(" ")} fill="#8CAE86" fillOpacity={.14} stroke="var(--gold)" strokeWidth={1.5}/>{traits.map((t,i)=>{const [cx,cy]=point(i,t.value/100);return <circle key={t.code} cx={cx} cy={cy} r={3} fill="var(--gold)"/>;})}</svg><p className="chart-note">Шкала 0–100. Это баллы теста,<br/>а не процентили и не оценка «лучше — хуже».</p></div>
    <div className="traits-panel">{traits.map((t,i)=><button type="button" className="trait-button" key={t.code} aria-pressed={selected===i} aria-controls="atlas-trait-detail" aria-label={`${t.name}: ${t.value} из 100. Показать объяснение`} onClick={()=>setSelected(i)}><span className="trait-head"><span className="trait-code">{t.code}</span>{t.name}<span className="trait-value">{t.value}</span></span><span className="trait-track" aria-hidden="true"><span className="trait-fill" style={{width:`${t.value}%`}}/><span className="trait-tick"/></span><span className="trait-poles" aria-hidden="true"><span>{t.poles[0]}</span><span>{t.poles[1]}</span></span></button>)}<div id="atlas-trait-detail" className="trait-detail" role="status"><strong>{traits[selected]!.name} · {traits[selected]!.value}/100</strong>{traits[selected]!.description} {traits[selected]!.key==="stability"&&"Показатель не описывает состояние здоровья и не гарантирует определённую реакцию."}</div></div></div>
    <div className="insight-band"><div><span className="eyebrow gold">Моё сочетание</span><h3>{model.strengths[0]!.title}</h3></div><div className="combination" aria-label={`Основания: ${model.strengths[0]!.basis.join(" и ")}`}>{model.strengths[0]!.basis.map((basis,i)=><span key={basis}>{i>0?"+ ":""}{basis}</span>)}<i>=</i><span className="combo-result">Практика<br/>и наблюдение</span></div><p>{model.strengths[0]!.explanation} Возможный перегиб: {model.strengths[0]!.risk}</p></div>
    <details className="interpretation"><summary>Как читать эту формулу</summary><p>Интерпретации — редакционные гипотезы для самонаблюдения, а не достоверные предсказания поведения. Учитывай опыт, навыки и условия задачи. Ни один полюс не является «правильным».</p><p>Категории теста: 0–44 — низкий уровень, 45–55 — пограничный, 56–100 — высокий. Матрица v0.3 выбирает содержание и не меняет твои баллы.</p></details>
  </Section>;
}
