"use client";
import { useEffect, useRef, useState } from "react";
import type { GemAssetDir } from "@/lib/gem-assets";
import type { PersonalityAtlas as AtlasModel } from "@/lib/personality-atlas";
import { GemPortrait } from "@/components/GemPortrait";
import { AtlasNavigation } from "./AtlasNavigation";
import { AtlasFormula } from "./AtlasFormula";
import { Section, SmallGem, Tabs } from "./AtlasPrimitives";
import { AtlasScenarios, AtlasWeek } from "./AtlasPractices";
import { AtlasInteraction, AtlasMemo } from "./AtlasEditableCards";
import { ATLAS_COPY } from "./atlas-copy";
import { useAtlasDraft, type ClientAtlasDraft, type SaveState } from "./use-atlas-draft";
import styles from "./PersonalityAtlas.module.css";

type Props={resultId:string;displayName:string;typeName:string;typeCode:string;gemDir:GemAssetDir;model:AtlasModel;initialDraft:ClientAtlasDraft};
const labels:Record<SaveState,string>={idle:"Изменений пока нет",dirty:"Есть несохранённые правки",saving:"Сохраняем…",saved:"Сохранено в вашем аккаунте",error:"Сохранение не подтверждено",conflict:"Есть другая версия на сервере"};
const energyPaths=["M5 32h18 M77 32h18 M50 9a23 23 0 1 0 0 46a23 23 0 1 0 0-46 M50 18a14 14 0 1 0 0 28a14 14 0 1 0 0-28","M5 42H22V20H41V42H60V12H79V42H95 M5 55H95","M12 14H56V40H25L12 49Z M44 25H87V51H74L87 61V51","M10 50 35 50 35 30 63 30 63 13 90 13 M35 30H63V51H90"];

export function PersonalityAtlas({resultId,displayName,typeName,typeCode,gemDir,model,initialDraft}:Props){
  const draft=useAtlasDraft(resultId,initialDraft);const [step,setStep]=useState(0),[mode,setMode]=useState(0),[notice,setNotice]=useState("");
  const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const [ready,setReady]=useState(false);
  useEffect(()=>setReady(true),[]);
  const done=draft.data.done.filter(Boolean).length;
  useEffect(()=>()=>{if(toastTimer.current)clearTimeout(toastTimer.current);},[]);
  const notify=(text:string)=>{if(toastTimer.current)clearTimeout(toastTimer.current);setNotice(text);toastTimer.current=setTimeout(()=>setNotice(""),6000);};
  const backup=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({resultId,data:draft.data},null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="Грани-приватный-черновик.json";document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);};
  return <div className={styles.root} data-atlas-ready={ready?true:undefined}>
    <a className="skip" href="#atlas-section-1">Перейти к формуле личности</a>
    <div className="layout"><AtlasNavigation done={done}/><div className="atlas-main">
      <div className="demo-notice"><span className="notice-symbol" aria-hidden="true">◇</span><div><strong>Ваш приватный атлас.</strong> Баллы — из ваших ответов в тесте. Интерпретации — гипотезы для самонаблюдения.</div><a href="#atlas-save-status">Сохранение</a></div>
      <div className="storage-bar" id="atlas-save-status"><div><strong className="save-status" role="status">{ready?labels[draft.status]:"Загружаем инструменты…"}</strong><p>Карточка, памятка, отметки и заметки приватны. Изменения сохраняются автоматически. {draft.localRecoveryAvailable?"Несохранённый черновик временно хранится только в этой вкладке.":"Браузер запретил временное хранение. Сохраните правки на сервер или скачайте черновик перед уходом; восстановление после перезагрузки недоступно."}</p></div><div className="save-actions"><button type="button" className="text-button" onClick={()=>void draft.saveNow()} disabled={draft.status==="saving"||draft.status==="conflict"||draft.status==="error"}>Сохранить сейчас</button>{draft.status==="error"&&<button type="button" className="button ghost" onClick={draft.retry}>Повторить сохранение</button>}{draft.status==="conflict"&&<button type="button" className="button ghost" onClick={()=>{if(window.confirm("Загрузить серверную версию? Несохранённые правки в этой вкладке будут заменены. Сначала можно скачать черновик."))void draft.loadServer();}}>Загрузить серверную версию</button>}{["error","conflict"].includes(draft.status)&&<button type="button" className="button ghost" onClick={backup}>Скачать черновик</button>}{["error","conflict"].includes(draft.status)&&<button type="button" className="text-button" onClick={()=>{if(window.confirm("Выйти без сохранения? Правки, которые не записаны на сервер, и неприменённый текст редакторов будут потеряны. Перед выходом можно скачать черновик применённых правок."))draft.leaveWithoutSaving();}}>Выйти без сохранения</button>}</div></div>{draft.message&&<p className="field-help" role="alert">{draft.message}</p>}
      <header className="overview" id="atlas-overview"><div className="hero-copy"><p className="eyebrow gold">{displayName} · {typeName} · {typeCode}</p><h1>Мои грани<span>инструкция к себе</span></h1><p className="hero-lead">{model.theme}</p><p className="muted hero-description">Девять ракурсов твоего характера.<br/>Чтобы замечать свои возможности и выбирать,<br/>как пользоваться ими в жизни.</p><a className="button primary" href="#atlas-section-1">Открыть мою формулу ↓</a></div><div className="hero-stone" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><GemPortrait dir={gemDir} size={400} priority/><span className="stone-caption">{typeName}</span></div><div className="hero-bottom"><span>Твой характер — больше, чем тип</span><span>5 шкал · 9 разделов · 7 дней практики</span></div></header>
      <fieldset className="atlas-controls" disabled={!ready} aria-label="Интерактивные разделы атласа">
      <AtlasFormula model={model}/>
      <Section number={2} label="Три мои суперсилы" title="То, на что можно опереться"><p className="section-intro">Три возможных ресурса, которые стоит проверить в знакомых задачах.</p><div className="strength-grid">{model.strengths.map((insight,i)=><article className="strength-card" key={insight.id}><SmallGem index={i}/><h3>{insight.title}</h3><p>{insight.explanation}</p><span className="basis">Основания: {insight.basis.join(" · ")}</span><details><summary>Как использовать</summary><p><strong>Применение.</strong> {insight.application}</p><p><strong>Что попробовать.</strong> {insight.practice}</p><p><strong>Граница интерпретации.</strong> {insight.limit}</p></details></article>)}</div></Section>
      <Section number={3} label="Когда сильные стороны мешают" title="Сила тоже нуждается в мере"><p className="section-intro">Та же привычка может помогать в одной ситуации и затруднять другую. Посмотри, узнаёшь ли ты себя.</p><div className="overreach-labels" aria-hidden="true"><span>Сила</span><span>Возможный перегиб</span><span>Что попробовать</span></div>{model.strengths.map(s=><article className="overreach-row" key={s.id}><div><h3>{s.title}</h3><span className="basis">{s.basis.join(" · ")}</span></div><p className="risk">{s.risk}</p><p className="try">{s.practice}</p><details><summary>Проверить в своей ситуации</summary><p>Выбери одну знакомую задачу. Сравни результат привычного способа и небольшой практики. {s.limit}</p></details></article>)}</Section>
      <Section number={4} label="Как я принимаю решения" title="От вариантов — к проверке"><p className="section-intro">При следующем непростом выборе ограничь количество вариантов и оцени, полезен ли тебе такой подход.</p><div className="decision-panel"><Tabs prefix="atlas-step" items={ATLAS_COPY.decisions.map(s=>s.title)} selected={step} onSelect={setStep} label="Пять шагов принятия решения" panel="atlas-decision-detail" className="decision-steps" numbers/><div id="atlas-decision-detail" role="tabpanel" aria-labelledby={`atlas-step-${step}`} tabIndex={0}><h3>{ATLAS_COPY.decisions[step]!.title}</h3><p>{ATLAS_COPY.decisions[step]!.text}</p><p className="prompt">{ATLAS_COPY.decisions[step]!.prompt}</p></div><label className="field-label" htmlFor="atlas-decision-note">Мой следующий непростой выбор</label><textarea id="atlas-decision-note" rows={3} maxLength={2000} value={draft.data.decision} onChange={e=>draft.update(before=>({...before,decision:e.target.value}))} placeholder="Какой результат сейчас действительно нужен?"/><p className="field-help">Это рабочая заметка, а не рекомендация системы.</p></div></Section>
      <Section number={5} label="Моя энергия и продуктивность" title="Найти свой рабочий ритм"><p className="section-intro">Четыре эксперимента с организацией дня. Big Five не определяет физиологическую энергию и не объясняет состояние здоровья.</p><div className="energy-grid">{ATLAS_COPY.energy.map((s,i)=><article className="energy-card" key={s.title}><svg viewBox="0 0 100 70" aria-hidden="true"><path d={energyPaths[i]}/></svg><h3>{s.title}</h3><p>{s.text}</p><p className="energy-tip">{s.tip}</p></article>)}</div><div className="rhythm-panel"><div><p className="eyebrow gold">Проверить на практике</p><h3>Как начать задачу?</h3><p className="muted">Сравни два режима на похожих задачах.</p></div><div><Tabs prefix="atlas-mode" items={["Сначала самостоятельно","Сначала обсудить"]} selected={mode} onSelect={setMode} label="Рабочий режим" panel="atlas-mode-detail"/><div id="atlas-mode-detail" role="tabpanel" aria-labelledby={`atlas-mode-${mode}`} tabIndex={0}><p>{mode===0?"Сформулируй своё решение до обсуждения. Затем сравни с другим мнением: что стало яснее, что пришлось пересмотреть?":"Начни с короткого обсуждения цели. Затем поработай самостоятельно: помог ли общий контекст выбрать следующий шаг?"}</p></div></div></div></Section>
      <AtlasInteraction resultId={resultId} data={draft.data} update={draft.update} displayName={displayName} notify={notify}/>
      <AtlasScenarios model={model}/><AtlasWeek data={draft.data} update={draft.update}/>
      <AtlasMemo resultId={resultId} data={draft.data} update={draft.update} model={model} displayName={displayName} typeName={typeName} notify={notify} prepareExport={draft.prepareExport}/>
      </fieldset>
      <footer className="atlas-footer"><p>Материалы для самопознания, не психологическая и не медицинская диагностика. Психологические интерпретации — редакционные гипотезы для самонаблюдения.</p><a href="#atlas-overview">К началу атласа ↑</a></footer>
    </div></div>{notice&&<div className="toast" role="status">{notice}</div>}
  </div>;
}
